---
- name: Update apt cache
  apt:
    update_cache: true

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
    state: present

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Install Docker Engine
  apt:
    name: docker-ce
    state: present
  when: ansible_os_family == "Debian"

- name: Install Docker SDK for Python
  pip:
    name:
      - requests==2.28.2
      - docker==6.1.3
    state: present
